# 1.声明

In [2]:
import numpy as np
a = np.array([2,4,5,6,7,9])
a[0:6:2]

array([2, 5, 7])

In [3]:
np.arange(4)

array([0, 1, 2, 3])

In [4]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# 2.操作

In [7]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6]])
a = np.concatenate((x,y),axis=0)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [30]:
b = np.arange(6)


array([0, 1, 2, 3, 4, 5])

In [66]:
b1 = b.reshape(2,3)
b1

array([[0, 1, 2],
       [3, 4, 5]])

In [67]:
b[1] = 99
b1

array([[ 0, 99,  2],
       [ 3,  4,  5]])

In [37]:
c = np.expand_dims(b,1)
c.shape

(6, 1)

# 3数据筛选

In [40]:
d = np.arange(12)
[d>3]
d[d<3]

array([0, 1, 2])

In [56]:
e = np.array([[1,2,3,4],
        [5,6,7,8],
        [9,10,11,12]])
f = np.nonzero(e<5)
e[f]


array([1, 2, 3, 4])

# 4堆叠,拆分矩阵


In [62]:
g = np.array([[1,1],
             [2,2]])
h = np.array([[3,3],
             [4,4]])
i = np.vstack((g,h))
i

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [63]:
np.vsplit(i,2)

[array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]])]

In [64]:
np.vsplit(i,(1,3))

[array([[1, 1]]),
 array([[2, 2],
        [3, 3]]),
 array([[4, 4]])]

# 5.重复元素过滤

In [71]:
j = np.array([0,0,0,1,1,2,3,4,5])
j_nique,index = np.unique(j,return_index=True)
j_nique
index

array([0, 3, 5, 6, 7, 8], dtype=int64)

# 6.转置

In [74]:
k = np.arange(6)

In [76]:
k1 = k.reshape(2,3)
k1

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
k1.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [79]:
np.flip(k1)

array([[5, 4, 3],
       [2, 1, 0]])

# 7.数组的加载和保存


In [85]:
l = np.array([1,2,3,4,5,6])
np.savetxt('./npdata.csv',l)

In [83]:
m = np.load('./npdata.npy')
m

array([1, 2, 3, 4, 5, 6])